### PR TITLE
Change binding syntax to ${}

### LINKED ISSUE #46: Consider a different binding character
Instead of `{{foo}}` which is familiar but also a little bit noisy, I kind of like `[foo]`.  Need to make sure we support escape characters.  Just an idea! Not going to implement this yet.

### PR DESCRIPTION
**Pull request by matthewp**
This does two things:

1. Changes the binding syntax from `{{foo}}` to `${foo}`. The main
reason for this is that it is familiar now that JavaScript template
literals use this syntax. And the older binding syntax has some negative
feelings among people who disliked traditional templating languages for
various reasons.

2. Removes the need for using binding syntax in `if` and `each`. So
instead of `if="{{condition}}"` you can just do `if="condition"`.

The ultimate goal is to make everything as HTML-first as possible,
    removing special syntax whenver possible. To that end we'll continue
    what the `on-` event handlers do; remove special characters and go
    with conventions.

Closes #46

### CODE REVIEW

**Comment by matthewp** [comment]
Note that this can't be merged until [this codepen](https://codepen.io/matthewp/pen/dNybdG?editors=1010) is updated. And to do that I need to do a prerelease.

**Comment by bedeoverend** [comment]
FWIW I'm generally against using syntaxes that are the same as another language feature, when they don't have the exact same behaviour i.e. I get unexpected behaviour. For example, Seeing that in a template, I'd immediately think I'd be able to do JS expressions, though in reality it's binding so (I assume) that wouldn't have the desired effect. 

If you use the same binding syntax, I'd expect the same functionality. Having said that, I'm not very familiar with Bram's templating / binding behaviour, so take this all with a grain of salt 😜

**Comment by matthewp** [comment]
No, this is very valuable feedback! I'm going to explore what others in this space are doing before making a decision on this. My goal is to:

1. Have as little syntax as possible. #2 does this but likely still need some syntax for textnodes and attributes.
2. Where syntax is needed, make it obvious.
3. Move away from mustache curls and the assumptions it comes with (like blocks, which of course we don't have).

**Comment by matthewp** [comment]
You present quite the conundrum :) . On the one hand I agree that the `${}` syntax might make people believe that JavaScript expressions can be used, and that's not something I want to support (I'm a believer of doing your JavaScript in your JavaScript).

On the other hand, the best alternative I see is `[foo]` but that unfortunately is a no-go because people will use `<style>` tags in their template and will therefore be using brackets for attribute selectors.  Unless I tried something crazy like parse the CSS to be able to distinguish between attribute selectors and other bindings... that seems pretty hard though!

So I'm not sure what to do! Still thinking. Might keep it as `{{}}` for now, but get rid of them in `if` and `each`, since that's a big win regardless.

**Comment by matthewp** [comment]
I've decided not to do this. Thanks @bedeoverend.  Biggest reason is that the limited discussion surrounding a standard binding syntax has used `{{` in the examples. Not sure if that is what will be used or not.. but if there's even a chance I'd rather stick with that for now.

**Comment by bedeoverend** [comment]
Apologies for not getting back sooner! FWIW I agree, `{{...}}` even if it has some issues, still most standard binding syntax, so at least people will GROK it quickly.

Can't think of any resolutions to other problems you've raised, I agree with them all though, particularly "_Have as little syntax as possible._" +1 +1. I'll chime in if I can think of anything worthwhile here.

**Pull request closed without merging**
